### ISSUE TITLE
play button hard to press on iOS 

### ISSUE THREAD

**Issue by wilding-radio** [wilding-radio/wilding-radio.github.io#5]
a few emails from people who seem to think the site is 'broken' after the update. I note on my phone (iphone 7, iOS 15.7.8) it is really hard - like basically impossible - to press play. Maybe from enlarging the bounding box on the slider? 
I've not got enough .js to fix it, could you take a look when you have a mo?

**Comment by maxbaraitsersmith** [comment]
Found the bug and fixed it!
